using System;
using System.IO;
using System.Text;
using UnityEngine;

namespace MeshLODGenerator
{
    /// <summary>
    /// Wavefront OBJ and MTL exporter for mesh LODs.
    /// Universal standard supported by virtually all 3D applications.
    /// </summary>
    public static class MeshLodObjExporter
    {
        public static bool ExportObj(string objPath, Mesh mesh, string albedoTexturePath = null)
        {
            if (string.IsNullOrEmpty(objPath) || mesh == null) return false;

            try
            {
                string dir = Path.GetDirectoryName(objPath);
                string baseName = Path.GetFileNameWithoutExtension(objPath);
                string mtlPath = Path.Combine(dir, baseName + ".mtl");
                string mtlFileName = Path.GetFileName(mtlPath);

                Vector3[] vertices = mesh.vertices;
                Vector3[] normals = mesh.normals;
                Vector2[] uvs = mesh.uv;
                int[] triangles = mesh.triangles;

                if (normals == null || normals.Length != vertices.Length)
                {
                    mesh.RecalculateNormals();
                    normals = mesh.normals;
                }

                // 1. Write MTL file
                StringBuilder mtl = new StringBuilder();
                mtl.AppendLine("# Material file generated by MeshLODGenerator");
                mtl.AppendLine($"newmtl {baseName}_Material");
                mtl.AppendLine("Ka 1.000 1.000 1.000");
                mtl.AppendLine("Kd 1.000 1.000 1.000");
                mtl.AppendLine("Ks 0.000 0.000 0.000");
                mtl.AppendLine("d 1.0");
                mtl.AppendLine("illum 2");
                if (!string.IsNullOrEmpty(albedoTexturePath))
                {
                    mtl.AppendLine($"map_Kd {Path.GetFileName(albedoTexturePath)}");
                }
                File.WriteAllText(mtlPath, mtl.ToString());

                // 2. Write OBJ file
                StringBuilder obj = new StringBuilder();
                obj.AppendLine("# OBJ file generated by MeshLODGenerator");
                obj.AppendLine($"mtllib {mtlFileName}");
                obj.AppendLine($"o {baseName}");

                // Vertices (negate Z for LHS -> RHS)
                for (int i = 0; i < vertices.Length; i++)
                {
                    Vector3 v = vertices[i];
                    obj.AppendLine($"v {v.x:F6} {v.y:F6} {-v.z:F6}");
                }

                // UVs
                if (uvs != null && uvs.Length == vertices.Length)
                {
                    for (int i = 0; i < uvs.Length; i++)
                    {
                        Vector2 uv = uvs[i];
                        obj.AppendLine($"vt {uv.x:F6} {uv.y:F6}");
                    }
                }

                // Normals
                for (int i = 0; i < normals.Length; i++)
                {
                    Vector3 n = normals[i];
                    obj.AppendLine($"vn {n.x:F6} {n.y:F6} {-n.z:F6}");
                }

                obj.AppendLine($"usemtl {baseName}_Material");
                obj.AppendLine("s 1");

                // Faces (1-indexed, winding flip)
                bool hasUv = uvs != null && uvs.Length == vertices.Length;
                for (int i = 0; i < triangles.Length; i += 3)
                {
                    int a = triangles[i] + 1;
                    int b = triangles[i + 2] + 1;
                    int c = triangles[i + 1] + 1;
                    if (hasUv)
                    {
                        obj.AppendLine($"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}");
                    }
                    else
                    {
                        obj.AppendLine($"f {a}//{a} {b}//{b} {c}//{c}");
                    }
                }

                File.WriteAllText(objPath, obj.ToString());
                Debug.Log($"[MeshLodObjExporter] Exported OBJ to: {objPath}");
                return true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[MeshLodObjExporter] OBJ export failed: {ex.Message}");
                return false;
            }
        }
    }
}
